%YAML 1.2
--- |
  # Copyright 2016 gRPC authors.
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  
  FROM debian:jessie
  
  <%include file="../../apt_get_basic.include"/>
  <%include file="../../gcp_api_libraries.include"/>
  <%include file="../../csharp_deps.include"/>
  <%include file="../../csharp_dotnetcli_deps.include"/>
  <%include file="../../cxx_deps.include"/>
  <%include file="../../node_deps.include"/>
  <%include file="../../php_deps.include"/>
  <%include file="../../ruby_deps.include"/>
  # lidiz: There is a conflict of binutils while installing different
  # version of Python, I remove it here to enable it to be upgraded later.
  # libc6-dev : Breaks: binutils (< 2.26) but 2.25-5+deb8u1 is to be installed
  RUN apt-get remove -y binutils
  <%include file="../../apt_get_python_27.include"/>
  # Install Python 3.7 with pip and virtualenv
  <%include file="../../debian_testing_repo.include"/>
  RUN apt-get update && apt-get -t testing install -y python3.7 python3-all-dev
  RUN curl https://bootstrap.pypa.io/get-pip.py | python3.7
  RUN python3.7 -m pip install virtualenv
  
  # Install coverage for Python test coverage reporting
  RUN pip install coverage
  ENV PATH ~/.local/bin:$PATH

  # Install Mako to generate files in grpc/grpc-node
  RUN pip install Mako

  <%include file="../../run_tests_addons.include"/>
  # Define the default command.
  CMD ["bash"]
